export default [
    {
        "wfId": 3368,
        "wfNmeUnq": "wf_HIVE_DL_RAW_2_PG_CSR_full",
        "rlsStus": "SUCCEEDED",
        "rlsStartDt": "2018-12-15T15:00:07.449+0000",
        "rlsEndDt": "2018-12-15T15:02:27.481+0000",
        "rlsRunInf": null,
        "rlsParams": "{}",
        "rlsJobId": null,
        "rlsErrMsg": null
    },
    {
        "wfId": 3578,
        "wfNmeUnq": "wf_HIVE_DL_RAW_2_PHOENIX_PNX_DL_MART_full",
        "rlsStus": "SUCCEEDED",
        "rlsStartDt": "2018-12-15T00:50:37.479+0000",
        "rlsEndDt": "2018-12-15T01:19:27.473+0000",
        "rlsRunInf": null,
        "rlsParams": "{}",
        "rlsJobId": null,
        "rlsErrMsg": null
    },
    {
        "wfId": 3534,
        "wfNmeUnq": "wf_HIVE_DL_RAW_2_PHOENIX_PNX_DL_MART_friday_full",
        "rlsStus": "SUCCEEDED",
        "rlsStartDt": "2018-12-15T00:35:37.503+0000",
        "rlsEndDt": "2018-12-15T00:36:57.478+0000",
        "rlsRunInf": null,
        "rlsParams": "{}",
        "rlsJobId": null,
        "rlsErrMsg": null
    },
    {
        "wfId": 2000,
        "wfNmeUnq": "wf_EXADATA_CSR_2_HIVE_DL_RAW_full",
        "rlsStus": "SUCCEEDED",
        "rlsStartDt": "2018-12-15T00:30:17.823+0000",
        "rlsEndDt": "2018-12-15T00:50:27.471+0000",
        "rlsRunInf": null,
        "rlsParams": "{}",
        "rlsJobId": null,
        "rlsErrMsg": null
    },
    {
        "wfId": 2820,
        "wfNmeUnq": "wf_EXADATA_SMALL_TABLES_2_HIVE_DL_RAW_full",
        "rlsStus": "FINISHED",
        "rlsStartDt": "2018-12-15T00:30:17.788+0000",
        "rlsEndDt": "2018-12-15T00:46:37.535+0000",
        "rlsRunInf": null,
        "rlsParams": "{}",
        "rlsJobId": null,
        "rlsErrMsg": null
    },
    {
        "wfId": 5284,
        "wfNmeUnq": "wf_PHOENIX_TRMT_2_HIVE_DL_RAW_full",
        "rlsStus": "SUCCEEDED",
        "rlsStartDt": "2018-12-15T00:30:17.745+0000",
        "rlsEndDt": "2018-12-15T00:35:07.570+0000",
        "rlsRunInf": null,
        "rlsParams": "{}",
        "rlsJobId": null,
        "rlsErrMsg": null
    },
    {
        "wfId": 5214,
        "wfNmeUnq": "wf_PHOENIX_DEFAULT_2_HIVE_DL_RAW_full",
        "rlsStus": "SUCCEEDED",
        "rlsStartDt": "2018-12-15T00:30:17.716+0000",
        "rlsEndDt": "2018-12-15T00:35:27.462+0000",
        "rlsRunInf": null,
        "rlsParams": "{}",
        "rlsJobId": null,
        "rlsErrMsg": null
    },
    {
        "wfId": 5152,
        "wfNmeUnq": "wf_PG_DICT_2_HIVE_DL_RAW_CA_full",
        "rlsStus": "SUCCEEDED",
        "rlsStartDt": "2018-12-15T00:30:17.514+0000",
        "rlsEndDt": "2018-12-15T00:34:07.562+0000",
        "rlsRunInf": null,
        "rlsParams": "{}",
        "rlsJobId": null,
        "rlsErrMsg": null
    },
    {
        "wfId": 5102,
        "wfNmeUnq": "wf_KKT_PG_EIAP_2_HIVE_DL_TECH_incr",
        "rlsStus": null,
        "rlsStartDt": null,
        "rlsEndDt": null,
        "rlsRunInf": null,
        "rlsParams": null,
        "rlsJobId": null,
        "rlsErrMsg": null
    },
    {
        "wfId": 17128,
        "wfNmeUnq": "wf_EXADATA_TAX_OBJ_2_HIVE_DL_RAW_incr",
        "rlsStus": null,
        "rlsStartDt": null,
        "rlsEndDt": null,
        "rlsRunInf": null,
        "rlsParams": null,
        "rlsJobId": null,
        "rlsErrMsg": null
    },
    {
        "wfId": 17328,
        "wfNmeUnq": "wf_redo_downloader_EXADATA_PUBLIC_2_HDFS_CSV_incr",
        "rlsStus": null,
        "rlsStartDt": null,
        "rlsEndDt": null,
        "rlsRunInf": null,
        "rlsParams": null,
        "rlsJobId": null,
        "rlsErrMsg": null
    },
    {
        "wfId": 17380,
        "wfNmeUnq": "wf_redo_trasformer_HIVE_DL_INTERFACE_2_HIVE_DL_RAW_incr",
        "rlsStus": null,
        "rlsStartDt": null,
        "rlsEndDt": null,
        "rlsRunInf": null,
        "rlsParams": null,
        "rlsJobId": null,
        "rlsErrMsg": null
    },
    {
        "wfId": 1600,
        "wfNmeUnq": "wf_EXADATA_TAX_OBJ_2_HIVE_DL_RAW_large_tables_full",
        "rlsStus": null,
        "rlsStartDt": null,
        "rlsEndDt": null,
        "rlsRunInf": null,
        "rlsParams": null,
        "rlsJobId": null,
        "rlsErrMsg": null
    },
    {
        "wfId": 20350,
        "wfNmeUnq": "wf_AC_manual_tasks_package",
        "rlsStus": null,
        "rlsStartDt": null,
        "rlsEndDt": null,
        "rlsRunInf": null,
        "rlsParams": null,
        "rlsJobId": null,
        "rlsErrMsg": null
    },
    {
        "wfId": 1802,
        "wfNmeUnq": "wf_EXADATA_TAX_OBJ_2_HIVE_DL_RAW_small_tables_full",
        "rlsStus": null,
        "rlsStartDt": null,
        "rlsEndDt": null,
        "rlsRunInf": null,
        "rlsParams": null,
        "rlsJobId": null,
        "rlsErrMsg": null
    },
    {
        "wfId": 3902,
        "wfNmeUnq": "wf_KKT_2_HIVE_DL_RAW_incr",
        "rlsStus": null,
        "rlsStartDt": null,
        "rlsEndDt": null,
        "rlsRunInf": null,
        "rlsParams": null,
        "rlsJobId": null,
        "rlsErrMsg": null
    },
    {
        "wfId": 4062,
        "wfNmeUnq": "wf_KKT_2_HIVE_DL_RAW_incr_hist",
        "rlsStus": null,
        "rlsStartDt": null,
        "rlsEndDt": null,
        "rlsRunInf": null,
        "rlsParams": null,
        "rlsJobId": null,
        "rlsErrMsg": null
    },
    {
        "wfId": 4142,
        "wfNmeUnq": "wf_KKT_HIVE_AGGs_KKT_2_PG_MART_incr_full",
        "rlsStus": null,
        "rlsStartDt": null,
        "rlsEndDt": null,
        "rlsRunInf": null,
        "rlsParams": null,
        "rlsJobId": null,
        "rlsErrMsg": null
    },
    {
        "wfId": 4220,
        "wfNmeUnq": "wf_KKT_HIVE_AGGs_KKT_2_PG_MART_incr_full_hist_rerun",
        "rlsStus": null,
        "rlsStartDt": null,
        "rlsEndDt": null,
        "rlsRunInf": null,
        "rlsParams": null,
        "rlsJobId": null,
        "rlsErrMsg": null
    },
    {
        "wfId": 4912,
        "wfNmeUnq": "wf_KKT_HIVE_DL_RAW_2_HIVE_DL_MART_incr",
        "rlsStus": null,
        "rlsStartDt": null,
        "rlsEndDt": null,
        "rlsRunInf": null,
        "rlsParams": null,
        "rlsJobId": null,
        "rlsErrMsg": null
    },
    {
        "wfId": 5034,
        "wfNmeUnq": "wf_KKT_HIVE_DL_RAW_2_HIVE_DL_MART_incr_rerun",
        "rlsStus": null,
        "rlsStartDt": null,
        "rlsEndDt": null,
        "rlsRunInf": null,
        "rlsParams": null,
        "rlsJobId": null,
        "rlsErrMsg": null
    }
]